//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pymex.MVC.InventarioProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntradaDC", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class EntradaDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.InventarioProxy.ProveedorDC ProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.InventarioProxy.HistorialSeguimientoDC HistorialSeguimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Pymex.MVC.InventarioProxy.EntradaDetalleDC> DetalleProductosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioAccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Pymex.MVC.InventarioProxy.ProveedorDC Proveedor {
            get {
                return this.ProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProveedorField, value) != true)) {
                    this.ProveedorField = value;
                    this.RaisePropertyChanged("Proveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Pymex.MVC.InventarioProxy.HistorialSeguimientoDC HistorialSeguimiento {
            get {
                return this.HistorialSeguimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.HistorialSeguimientoField, value) != true)) {
                    this.HistorialSeguimientoField = value;
                    this.RaisePropertyChanged("HistorialSeguimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Collections.Generic.List<Pymex.MVC.InventarioProxy.EntradaDetalleDC> DetalleProductos {
            get {
                return this.DetalleProductosField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleProductosField, value) != true)) {
                    this.DetalleProductosField = value;
                    this.RaisePropertyChanged("DetalleProductos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string UsuarioAccion {
            get {
                return this.UsuarioAccionField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioAccionField, value) != true)) {
                    this.UsuarioAccionField = value;
                    this.RaisePropertyChanged("UsuarioAccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProveedorDC", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ProveedorDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.InventarioProxy.TipoDocumento TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.InventarioProxy.HistorialSeguimientoDC HistorialSeguimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioAccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pymex.MVC.InventarioProxy.TipoDocumento TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((this.TipoDocumentoField.Equals(value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string NumeroDocumento {
            get {
                return this.NumeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDocumentoField, value) != true)) {
                    this.NumeroDocumentoField = value;
                    this.RaisePropertyChanged("NumeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string NombreCompleto {
            get {
                return this.NombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoField, value) != true)) {
                    this.NombreCompletoField = value;
                    this.RaisePropertyChanged("NombreCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Pymex.MVC.InventarioProxy.HistorialSeguimientoDC HistorialSeguimiento {
            get {
                return this.HistorialSeguimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.HistorialSeguimientoField, value) != true)) {
                    this.HistorialSeguimientoField = value;
                    this.RaisePropertyChanged("HistorialSeguimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string UsuarioAccion {
            get {
                return this.UsuarioAccionField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioAccionField, value) != true)) {
                    this.UsuarioAccionField = value;
                    this.RaisePropertyChanged("UsuarioAccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistorialSeguimientoDC", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.ValueObjects")]
    [System.SerializableAttribute()]
    public partial class HistorialSeguimientoDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UltimoUsuarioModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioRegistro {
            get {
                return this.UsuarioRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioRegistroField, value) != true)) {
                    this.UsuarioRegistroField = value;
                    this.RaisePropertyChanged("UsuarioRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string UltimoUsuarioModificacion {
            get {
                return this.UltimoUsuarioModificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UltimoUsuarioModificacionField, value) != true)) {
                    this.UltimoUsuarioModificacionField = value;
                    this.RaisePropertyChanged("UltimoUsuarioModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntradaDetalleDC", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class EntradaDetalleDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.InventarioProxy.ProductoDC ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioCompraUnidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioVentaUnidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pymex.MVC.InventarioProxy.ProductoDC Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal PrecioCompraUnidad {
            get {
                return this.PrecioCompraUnidadField;
            }
            set {
                if ((this.PrecioCompraUnidadField.Equals(value) != true)) {
                    this.PrecioCompraUnidadField = value;
                    this.RaisePropertyChanged("PrecioCompraUnidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal PrecioVentaUnidad {
            get {
                return this.PrecioVentaUnidadField;
            }
            set {
                if ((this.PrecioVentaUnidadField.Equals(value) != true)) {
                    this.PrecioVentaUnidadField = value;
                    this.RaisePropertyChanged("PrecioVentaUnidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDocumento", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.ValueObjects")]
    public enum TipoDocumento : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RUC = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DNI = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoDC", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ProductoDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.InventarioProxy.CategoriaDC CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.InventarioProxy.AlmacenDC AlmacenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UltimoPrecioCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UltimoPrecioVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.InventarioProxy.HistorialSeguimientoDC HistorialSeguimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioAccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Pymex.MVC.InventarioProxy.CategoriaDC Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Pymex.MVC.InventarioProxy.AlmacenDC Almacen {
            get {
                return this.AlmacenField;
            }
            set {
                if ((object.ReferenceEquals(this.AlmacenField, value) != true)) {
                    this.AlmacenField = value;
                    this.RaisePropertyChanged("Almacen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal UltimoPrecioCompra {
            get {
                return this.UltimoPrecioCompraField;
            }
            set {
                if ((this.UltimoPrecioCompraField.Equals(value) != true)) {
                    this.UltimoPrecioCompraField = value;
                    this.RaisePropertyChanged("UltimoPrecioCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal UltimoPrecioVenta {
            get {
                return this.UltimoPrecioVentaField;
            }
            set {
                if ((this.UltimoPrecioVentaField.Equals(value) != true)) {
                    this.UltimoPrecioVentaField = value;
                    this.RaisePropertyChanged("UltimoPrecioVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public Pymex.MVC.InventarioProxy.HistorialSeguimientoDC HistorialSeguimiento {
            get {
                return this.HistorialSeguimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.HistorialSeguimientoField, value) != true)) {
                    this.HistorialSeguimientoField = value;
                    this.RaisePropertyChanged("HistorialSeguimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string UsuarioAccion {
            get {
                return this.UsuarioAccionField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioAccionField, value) != true)) {
                    this.UsuarioAccionField = value;
                    this.RaisePropertyChanged("UsuarioAccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaDC", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class CategoriaDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlmacenDC", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class AlmacenDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AforoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Aforo {
            get {
                return this.AforoField;
            }
            set {
                if ((this.AforoField.Equals(value) != true)) {
                    this.AforoField = value;
                    this.RaisePropertyChanged("Aforo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDataContract", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfArrayOfSalidaDCXmnxQzc5))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfArrayOfEntradaDCXmnxQzc5))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfSalidaDCXmnxQzc5))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfEntradaDCXmnxQzc5))]
    public partial class ResponseDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsCorrectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsCorrecto {
            get {
                return this.EsCorrectoField;
            }
            set {
                if ((this.EsCorrectoField.Equals(value) != true)) {
                    this.EsCorrectoField = value;
                    this.RaisePropertyChanged("EsCorrecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithDataDataContractOfArrayOfSalidaDCXmnxQzc5", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ResponseWithDataDataContractOfArrayOfSalidaDCXmnxQzc5 : Pymex.MVC.InventarioProxy.ResponseDataContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Pymex.MVC.InventarioProxy.SalidaDC> DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Pymex.MVC.InventarioProxy.SalidaDC> Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithDataDataContractOfArrayOfEntradaDCXmnxQzc5", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ResponseWithDataDataContractOfArrayOfEntradaDCXmnxQzc5 : Pymex.MVC.InventarioProxy.ResponseDataContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Pymex.MVC.InventarioProxy.EntradaDC> DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Pymex.MVC.InventarioProxy.EntradaDC> Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithDataDataContractOfSalidaDCXmnxQzc5", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ResponseWithDataDataContractOfSalidaDCXmnxQzc5 : Pymex.MVC.InventarioProxy.ResponseDataContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.InventarioProxy.SalidaDC DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pymex.MVC.InventarioProxy.SalidaDC Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithDataDataContractOfEntradaDCXmnxQzc5", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ResponseWithDataDataContractOfEntradaDCXmnxQzc5 : Pymex.MVC.InventarioProxy.ResponseDataContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.InventarioProxy.EntradaDC DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pymex.MVC.InventarioProxy.EntradaDC Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalidaDC", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class SalidaDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.InventarioProxy.ClienteDC ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.InventarioProxy.HistorialSeguimientoDC HistorialSeguimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Pymex.MVC.InventarioProxy.SalidaDetalleDC> DetalleProductosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioAccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Pymex.MVC.InventarioProxy.ClienteDC Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Pymex.MVC.InventarioProxy.HistorialSeguimientoDC HistorialSeguimiento {
            get {
                return this.HistorialSeguimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.HistorialSeguimientoField, value) != true)) {
                    this.HistorialSeguimientoField = value;
                    this.RaisePropertyChanged("HistorialSeguimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Collections.Generic.List<Pymex.MVC.InventarioProxy.SalidaDetalleDC> DetalleProductos {
            get {
                return this.DetalleProductosField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleProductosField, value) != true)) {
                    this.DetalleProductosField = value;
                    this.RaisePropertyChanged("DetalleProductos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string UsuarioAccion {
            get {
                return this.UsuarioAccionField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioAccionField, value) != true)) {
                    this.UsuarioAccionField = value;
                    this.RaisePropertyChanged("UsuarioAccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteDC", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ClienteDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.InventarioProxy.TipoDocumento TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.InventarioProxy.HistorialSeguimientoDC HistorialSeguimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioAccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pymex.MVC.InventarioProxy.TipoDocumento TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((this.TipoDocumentoField.Equals(value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string NumeroDocumento {
            get {
                return this.NumeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDocumentoField, value) != true)) {
                    this.NumeroDocumentoField = value;
                    this.RaisePropertyChanged("NumeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string NombreCompleto {
            get {
                return this.NombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoField, value) != true)) {
                    this.NombreCompletoField = value;
                    this.RaisePropertyChanged("NombreCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Pymex.MVC.InventarioProxy.HistorialSeguimientoDC HistorialSeguimiento {
            get {
                return this.HistorialSeguimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.HistorialSeguimientoField, value) != true)) {
                    this.HistorialSeguimientoField = value;
                    this.RaisePropertyChanged("HistorialSeguimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string UsuarioAccion {
            get {
                return this.UsuarioAccionField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioAccionField, value) != true)) {
                    this.UsuarioAccionField = value;
                    this.RaisePropertyChanged("UsuarioAccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalidaDetalleDC", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class SalidaDetalleDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.InventarioProxy.ProductoDC ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioVentaUnidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pymex.MVC.InventarioProxy.ProductoDC Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal PrecioVentaUnidad {
            get {
                return this.PrecioVentaUnidadField;
            }
            set {
                if ((this.PrecioVentaUnidadField.Equals(value) != true)) {
                    this.PrecioVentaUnidadField = value;
                    this.RaisePropertyChanged("PrecioVentaUnidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InventarioProxy.IInventarioService")]
    public interface IInventarioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioService/RegistrarEntrada", ReplyAction="http://tempuri.org/IInventarioService/RegistrarEntradaResponse")]
        Pymex.MVC.InventarioProxy.ResponseDataContract RegistrarEntrada(Pymex.MVC.InventarioProxy.EntradaDC entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioService/RegistrarEntrada", ReplyAction="http://tempuri.org/IInventarioService/RegistrarEntradaResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.InventarioProxy.ResponseDataContract> RegistrarEntradaAsync(Pymex.MVC.InventarioProxy.EntradaDC entrada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioService/RegistrarSalida", ReplyAction="http://tempuri.org/IInventarioService/RegistrarSalidaResponse")]
        Pymex.MVC.InventarioProxy.ResponseDataContract RegistrarSalida(Pymex.MVC.InventarioProxy.SalidaDC salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioService/RegistrarSalida", ReplyAction="http://tempuri.org/IInventarioService/RegistrarSalidaResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.InventarioProxy.ResponseDataContract> RegistrarSalidaAsync(Pymex.MVC.InventarioProxy.SalidaDC salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioService/ListarSalidas", ReplyAction="http://tempuri.org/IInventarioService/ListarSalidasResponse")]
        Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfArrayOfSalidaDCXmnxQzc5 ListarSalidas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioService/ListarSalidas", ReplyAction="http://tempuri.org/IInventarioService/ListarSalidasResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfArrayOfSalidaDCXmnxQzc5> ListarSalidasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioService/ListarEntradas", ReplyAction="http://tempuri.org/IInventarioService/ListarEntradasResponse")]
        Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfArrayOfEntradaDCXmnxQzc5 ListarEntradas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioService/ListarEntradas", ReplyAction="http://tempuri.org/IInventarioService/ListarEntradasResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfArrayOfEntradaDCXmnxQzc5> ListarEntradasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioService/BuscarSalidaPorCodigo", ReplyAction="http://tempuri.org/IInventarioService/BuscarSalidaPorCodigoResponse")]
        Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfSalidaDCXmnxQzc5 BuscarSalidaPorCodigo(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioService/BuscarSalidaPorCodigo", ReplyAction="http://tempuri.org/IInventarioService/BuscarSalidaPorCodigoResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfSalidaDCXmnxQzc5> BuscarSalidaPorCodigoAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioService/BuscarEntradaPorCodigo", ReplyAction="http://tempuri.org/IInventarioService/BuscarEntradaPorCodigoResponse")]
        Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfEntradaDCXmnxQzc5 BuscarEntradaPorCodigo(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioService/BuscarEntradaPorCodigo", ReplyAction="http://tempuri.org/IInventarioService/BuscarEntradaPorCodigoResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfEntradaDCXmnxQzc5> BuscarEntradaPorCodigoAsync(string codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInventarioServiceChannel : Pymex.MVC.InventarioProxy.IInventarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InventarioServiceClient : System.ServiceModel.ClientBase<Pymex.MVC.InventarioProxy.IInventarioService>, Pymex.MVC.InventarioProxy.IInventarioService {
        
        public InventarioServiceClient() {
        }
        
        public InventarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InventarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pymex.MVC.InventarioProxy.ResponseDataContract RegistrarEntrada(Pymex.MVC.InventarioProxy.EntradaDC entrada) {
            return base.Channel.RegistrarEntrada(entrada);
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.InventarioProxy.ResponseDataContract> RegistrarEntradaAsync(Pymex.MVC.InventarioProxy.EntradaDC entrada) {
            return base.Channel.RegistrarEntradaAsync(entrada);
        }
        
        public Pymex.MVC.InventarioProxy.ResponseDataContract RegistrarSalida(Pymex.MVC.InventarioProxy.SalidaDC salida) {
            return base.Channel.RegistrarSalida(salida);
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.InventarioProxy.ResponseDataContract> RegistrarSalidaAsync(Pymex.MVC.InventarioProxy.SalidaDC salida) {
            return base.Channel.RegistrarSalidaAsync(salida);
        }
        
        public Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfArrayOfSalidaDCXmnxQzc5 ListarSalidas() {
            return base.Channel.ListarSalidas();
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfArrayOfSalidaDCXmnxQzc5> ListarSalidasAsync() {
            return base.Channel.ListarSalidasAsync();
        }
        
        public Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfArrayOfEntradaDCXmnxQzc5 ListarEntradas() {
            return base.Channel.ListarEntradas();
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfArrayOfEntradaDCXmnxQzc5> ListarEntradasAsync() {
            return base.Channel.ListarEntradasAsync();
        }
        
        public Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfSalidaDCXmnxQzc5 BuscarSalidaPorCodigo(string codigo) {
            return base.Channel.BuscarSalidaPorCodigo(codigo);
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfSalidaDCXmnxQzc5> BuscarSalidaPorCodigoAsync(string codigo) {
            return base.Channel.BuscarSalidaPorCodigoAsync(codigo);
        }
        
        public Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfEntradaDCXmnxQzc5 BuscarEntradaPorCodigo(string codigo) {
            return base.Channel.BuscarEntradaPorCodigo(codigo);
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.InventarioProxy.ResponseWithDataDataContractOfEntradaDCXmnxQzc5> BuscarEntradaPorCodigoAsync(string codigo) {
            return base.Channel.BuscarEntradaPorCodigoAsync(codigo);
        }
    }
}
