//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pymex.MVC.CategoriaProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDataContract", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pymex.MVC.CategoriaProxy.ResponseWithDataDataContractOfCategoriaDCXmnxQzc5))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pymex.MVC.CategoriaProxy.ResponseWithDataDataContractOfArrayOfCategoriaDCXmnxQzc5))]
    public partial class ResponseDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsCorrectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsCorrecto {
            get {
                return this.EsCorrectoField;
            }
            set {
                if ((this.EsCorrectoField.Equals(value) != true)) {
                    this.EsCorrectoField = value;
                    this.RaisePropertyChanged("EsCorrecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithDataDataContractOfCategoriaDCXmnxQzc5", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ResponseWithDataDataContractOfCategoriaDCXmnxQzc5 : Pymex.MVC.CategoriaProxy.ResponseDataContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.CategoriaProxy.CategoriaDC DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pymex.MVC.CategoriaProxy.CategoriaDC Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithDataDataContractOfArrayOfCategoriaDCXmnxQzc5", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ResponseWithDataDataContractOfArrayOfCategoriaDCXmnxQzc5 : Pymex.MVC.CategoriaProxy.ResponseDataContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.CategoriaProxy.CategoriaDC[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pymex.MVC.CategoriaProxy.CategoriaDC[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaDC", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class CategoriaDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CategoriaProxy.ICategoriaService")]
    public interface ICategoriaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_CategoriaDC/Listar", ReplyAction="http://tempuri.org/IGenericServiceOf_CategoriaDC/ListarResponse")]
        Pymex.MVC.CategoriaProxy.ResponseWithDataDataContractOfArrayOfCategoriaDCXmnxQzc5 Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_CategoriaDC/Listar", ReplyAction="http://tempuri.org/IGenericServiceOf_CategoriaDC/ListarResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.CategoriaProxy.ResponseWithDataDataContractOfArrayOfCategoriaDCXmnxQzc5> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_CategoriaDC/ObtenerPorId", ReplyAction="http://tempuri.org/IGenericServiceOf_CategoriaDC/ObtenerPorIdResponse")]
        Pymex.MVC.CategoriaProxy.ResponseWithDataDataContractOfCategoriaDCXmnxQzc5 ObtenerPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_CategoriaDC/ObtenerPorId", ReplyAction="http://tempuri.org/IGenericServiceOf_CategoriaDC/ObtenerPorIdResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.CategoriaProxy.ResponseWithDataDataContractOfCategoriaDCXmnxQzc5> ObtenerPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_CategoriaDC/Crear", ReplyAction="http://tempuri.org/IGenericServiceOf_CategoriaDC/CrearResponse")]
        Pymex.MVC.CategoriaProxy.ResponseDataContract Crear(Pymex.MVC.CategoriaProxy.CategoriaDC dataContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_CategoriaDC/Crear", ReplyAction="http://tempuri.org/IGenericServiceOf_CategoriaDC/CrearResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.CategoriaProxy.ResponseDataContract> CrearAsync(Pymex.MVC.CategoriaProxy.CategoriaDC dataContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_CategoriaDC/Actualizar", ReplyAction="http://tempuri.org/IGenericServiceOf_CategoriaDC/ActualizarResponse")]
        Pymex.MVC.CategoriaProxy.ResponseDataContract Actualizar(Pymex.MVC.CategoriaProxy.CategoriaDC dataContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_CategoriaDC/Actualizar", ReplyAction="http://tempuri.org/IGenericServiceOf_CategoriaDC/ActualizarResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.CategoriaProxy.ResponseDataContract> ActualizarAsync(Pymex.MVC.CategoriaProxy.CategoriaDC dataContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteOperationOf_CategoriaDC/Eliminar", ReplyAction="http://tempuri.org/IDeleteOperationOf_CategoriaDC/EliminarResponse")]
        Pymex.MVC.CategoriaProxy.ResponseDataContract Eliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteOperationOf_CategoriaDC/Eliminar", ReplyAction="http://tempuri.org/IDeleteOperationOf_CategoriaDC/EliminarResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.CategoriaProxy.ResponseDataContract> EliminarAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICategoriaServiceChannel : Pymex.MVC.CategoriaProxy.ICategoriaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoriaServiceClient : System.ServiceModel.ClientBase<Pymex.MVC.CategoriaProxy.ICategoriaService>, Pymex.MVC.CategoriaProxy.ICategoriaService {
        
        public CategoriaServiceClient() {
        }
        
        public CategoriaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoriaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pymex.MVC.CategoriaProxy.ResponseWithDataDataContractOfArrayOfCategoriaDCXmnxQzc5 Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.CategoriaProxy.ResponseWithDataDataContractOfArrayOfCategoriaDCXmnxQzc5> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public Pymex.MVC.CategoriaProxy.ResponseWithDataDataContractOfCategoriaDCXmnxQzc5 ObtenerPorId(int id) {
            return base.Channel.ObtenerPorId(id);
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.CategoriaProxy.ResponseWithDataDataContractOfCategoriaDCXmnxQzc5> ObtenerPorIdAsync(int id) {
            return base.Channel.ObtenerPorIdAsync(id);
        }
        
        public Pymex.MVC.CategoriaProxy.ResponseDataContract Crear(Pymex.MVC.CategoriaProxy.CategoriaDC dataContract) {
            return base.Channel.Crear(dataContract);
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.CategoriaProxy.ResponseDataContract> CrearAsync(Pymex.MVC.CategoriaProxy.CategoriaDC dataContract) {
            return base.Channel.CrearAsync(dataContract);
        }
        
        public Pymex.MVC.CategoriaProxy.ResponseDataContract Actualizar(Pymex.MVC.CategoriaProxy.CategoriaDC dataContract) {
            return base.Channel.Actualizar(dataContract);
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.CategoriaProxy.ResponseDataContract> ActualizarAsync(Pymex.MVC.CategoriaProxy.CategoriaDC dataContract) {
            return base.Channel.ActualizarAsync(dataContract);
        }
        
        public Pymex.MVC.CategoriaProxy.ResponseDataContract Eliminar(int id) {
            return base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.CategoriaProxy.ResponseDataContract> EliminarAsync(int id) {
            return base.Channel.EliminarAsync(id);
        }
    }
}
