//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pymex.MVC.ProductoProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDataContract", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfProductoDCXmnxQzc5))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfArrayOfProductoDCXmnxQzc5))]
    public partial class ResponseDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsCorrectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsCorrecto {
            get {
                return this.EsCorrectoField;
            }
            set {
                if ((this.EsCorrectoField.Equals(value) != true)) {
                    this.EsCorrectoField = value;
                    this.RaisePropertyChanged("EsCorrecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithDataDataContractOfProductoDCXmnxQzc5", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ResponseWithDataDataContractOfProductoDCXmnxQzc5 : Pymex.MVC.ProductoProxy.ResponseDataContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.ProductoProxy.ProductoDC DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pymex.MVC.ProductoProxy.ProductoDC Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithDataDataContractOfArrayOfProductoDCXmnxQzc5", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ResponseWithDataDataContractOfArrayOfProductoDCXmnxQzc5 : Pymex.MVC.ProductoProxy.ResponseDataContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.ProductoProxy.ProductoDC[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pymex.MVC.ProductoProxy.ProductoDC[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoDC", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ProductoDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.ProductoProxy.CategoriaDC CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.ProductoProxy.AlmacenDC AlmacenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UltimoPrecioCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UltimoPrecioVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.ProductoProxy.HistorialSeguimientoDC HistorialSeguimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioAccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Pymex.MVC.ProductoProxy.CategoriaDC Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Pymex.MVC.ProductoProxy.AlmacenDC Almacen {
            get {
                return this.AlmacenField;
            }
            set {
                if ((object.ReferenceEquals(this.AlmacenField, value) != true)) {
                    this.AlmacenField = value;
                    this.RaisePropertyChanged("Almacen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal UltimoPrecioCompra {
            get {
                return this.UltimoPrecioCompraField;
            }
            set {
                if ((this.UltimoPrecioCompraField.Equals(value) != true)) {
                    this.UltimoPrecioCompraField = value;
                    this.RaisePropertyChanged("UltimoPrecioCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal UltimoPrecioVenta {
            get {
                return this.UltimoPrecioVentaField;
            }
            set {
                if ((this.UltimoPrecioVentaField.Equals(value) != true)) {
                    this.UltimoPrecioVentaField = value;
                    this.RaisePropertyChanged("UltimoPrecioVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public Pymex.MVC.ProductoProxy.HistorialSeguimientoDC HistorialSeguimiento {
            get {
                return this.HistorialSeguimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.HistorialSeguimientoField, value) != true)) {
                    this.HistorialSeguimientoField = value;
                    this.RaisePropertyChanged("HistorialSeguimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string UsuarioAccion {
            get {
                return this.UsuarioAccionField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioAccionField, value) != true)) {
                    this.UsuarioAccionField = value;
                    this.RaisePropertyChanged("UsuarioAccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaDC", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class CategoriaDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlmacenDC", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class AlmacenDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AforoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Aforo {
            get {
                return this.AforoField;
            }
            set {
                if ((this.AforoField.Equals(value) != true)) {
                    this.AforoField = value;
                    this.RaisePropertyChanged("Aforo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistorialSeguimientoDC", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.ValueObjects")]
    [System.SerializableAttribute()]
    public partial class HistorialSeguimientoDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UltimoUsuarioModificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioRegistro {
            get {
                return this.UsuarioRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioRegistroField, value) != true)) {
                    this.UsuarioRegistroField = value;
                    this.RaisePropertyChanged("UsuarioRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string UltimoUsuarioModificacion {
            get {
                return this.UltimoUsuarioModificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UltimoUsuarioModificacionField, value) != true)) {
                    this.UltimoUsuarioModificacionField = value;
                    this.RaisePropertyChanged("UltimoUsuarioModificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductoProxy.IProductoService")]
    public interface IProductoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_ProductoDC/Listar", ReplyAction="http://tempuri.org/IGenericServiceOf_ProductoDC/ListarResponse")]
        Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfArrayOfProductoDCXmnxQzc5 Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_ProductoDC/Listar", ReplyAction="http://tempuri.org/IGenericServiceOf_ProductoDC/ListarResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfArrayOfProductoDCXmnxQzc5> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_ProductoDC/ObtenerPorId", ReplyAction="http://tempuri.org/IGenericServiceOf_ProductoDC/ObtenerPorIdResponse")]
        Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfProductoDCXmnxQzc5 ObtenerPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_ProductoDC/ObtenerPorId", ReplyAction="http://tempuri.org/IGenericServiceOf_ProductoDC/ObtenerPorIdResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfProductoDCXmnxQzc5> ObtenerPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_ProductoDC/Crear", ReplyAction="http://tempuri.org/IGenericServiceOf_ProductoDC/CrearResponse")]
        Pymex.MVC.ProductoProxy.ResponseDataContract Crear(Pymex.MVC.ProductoProxy.ProductoDC dataContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_ProductoDC/Crear", ReplyAction="http://tempuri.org/IGenericServiceOf_ProductoDC/CrearResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.ProductoProxy.ResponseDataContract> CrearAsync(Pymex.MVC.ProductoProxy.ProductoDC dataContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_ProductoDC/Actualizar", ReplyAction="http://tempuri.org/IGenericServiceOf_ProductoDC/ActualizarResponse")]
        Pymex.MVC.ProductoProxy.ResponseDataContract Actualizar(Pymex.MVC.ProductoProxy.ProductoDC dataContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_ProductoDC/Actualizar", ReplyAction="http://tempuri.org/IGenericServiceOf_ProductoDC/ActualizarResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.ProductoProxy.ResponseDataContract> ActualizarAsync(Pymex.MVC.ProductoProxy.ProductoDC dataContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListarPorCantidadOperationOf_ProductoDC/ListarPorExpresionYCa" +
            "ntidad", ReplyAction="http://tempuri.org/IListarPorCantidadOperationOf_ProductoDC/ListarPorExpresionYCa" +
            "ntidadResponse")]
        Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfArrayOfProductoDCXmnxQzc5 ListarPorExpresionYCantidad(string expresion, int maxCantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListarPorCantidadOperationOf_ProductoDC/ListarPorExpresionYCa" +
            "ntidad", ReplyAction="http://tempuri.org/IListarPorCantidadOperationOf_ProductoDC/ListarPorExpresionYCa" +
            "ntidadResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfArrayOfProductoDCXmnxQzc5> ListarPorExpresionYCantidadAsync(string expresion, int maxCantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ObtenerPorCodigo", ReplyAction="http://tempuri.org/IProductoService/ObtenerPorCodigoResponse")]
        Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfProductoDCXmnxQzc5 ObtenerPorCodigo(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ObtenerPorCodigo", ReplyAction="http://tempuri.org/IProductoService/ObtenerPorCodigoResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfProductoDCXmnxQzc5> ObtenerPorCodigoAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ListarSoloActivos", ReplyAction="http://tempuri.org/IProductoService/ListarSoloActivosResponse")]
        Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfArrayOfProductoDCXmnxQzc5 ListarSoloActivos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ListarSoloActivos", ReplyAction="http://tempuri.org/IProductoService/ListarSoloActivosResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfArrayOfProductoDCXmnxQzc5> ListarSoloActivosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ActivarPorCodigo", ReplyAction="http://tempuri.org/IProductoService/ActivarPorCodigoResponse")]
        Pymex.MVC.ProductoProxy.ResponseDataContract ActivarPorCodigo(Pymex.MVC.ProductoProxy.ProductoDC producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoService/ActivarPorCodigo", ReplyAction="http://tempuri.org/IProductoService/ActivarPorCodigoResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.ProductoProxy.ResponseDataContract> ActivarPorCodigoAsync(Pymex.MVC.ProductoProxy.ProductoDC producto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductoServiceChannel : Pymex.MVC.ProductoProxy.IProductoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoServiceClient : System.ServiceModel.ClientBase<Pymex.MVC.ProductoProxy.IProductoService>, Pymex.MVC.ProductoProxy.IProductoService {
        
        public ProductoServiceClient() {
        }
        
        public ProductoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfArrayOfProductoDCXmnxQzc5 Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfArrayOfProductoDCXmnxQzc5> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfProductoDCXmnxQzc5 ObtenerPorId(int id) {
            return base.Channel.ObtenerPorId(id);
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfProductoDCXmnxQzc5> ObtenerPorIdAsync(int id) {
            return base.Channel.ObtenerPorIdAsync(id);
        }
        
        public Pymex.MVC.ProductoProxy.ResponseDataContract Crear(Pymex.MVC.ProductoProxy.ProductoDC dataContract) {
            return base.Channel.Crear(dataContract);
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.ProductoProxy.ResponseDataContract> CrearAsync(Pymex.MVC.ProductoProxy.ProductoDC dataContract) {
            return base.Channel.CrearAsync(dataContract);
        }
        
        public Pymex.MVC.ProductoProxy.ResponseDataContract Actualizar(Pymex.MVC.ProductoProxy.ProductoDC dataContract) {
            return base.Channel.Actualizar(dataContract);
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.ProductoProxy.ResponseDataContract> ActualizarAsync(Pymex.MVC.ProductoProxy.ProductoDC dataContract) {
            return base.Channel.ActualizarAsync(dataContract);
        }
        
        public Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfArrayOfProductoDCXmnxQzc5 ListarPorExpresionYCantidad(string expresion, int maxCantidad) {
            return base.Channel.ListarPorExpresionYCantidad(expresion, maxCantidad);
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfArrayOfProductoDCXmnxQzc5> ListarPorExpresionYCantidadAsync(string expresion, int maxCantidad) {
            return base.Channel.ListarPorExpresionYCantidadAsync(expresion, maxCantidad);
        }
        
        public Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfProductoDCXmnxQzc5 ObtenerPorCodigo(string codigo) {
            return base.Channel.ObtenerPorCodigo(codigo);
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfProductoDCXmnxQzc5> ObtenerPorCodigoAsync(string codigo) {
            return base.Channel.ObtenerPorCodigoAsync(codigo);
        }
        
        public Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfArrayOfProductoDCXmnxQzc5 ListarSoloActivos() {
            return base.Channel.ListarSoloActivos();
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.ProductoProxy.ResponseWithDataDataContractOfArrayOfProductoDCXmnxQzc5> ListarSoloActivosAsync() {
            return base.Channel.ListarSoloActivosAsync();
        }
        
        public Pymex.MVC.ProductoProxy.ResponseDataContract ActivarPorCodigo(Pymex.MVC.ProductoProxy.ProductoDC producto) {
            return base.Channel.ActivarPorCodigo(producto);
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.ProductoProxy.ResponseDataContract> ActivarPorCodigoAsync(Pymex.MVC.ProductoProxy.ProductoDC producto) {
            return base.Channel.ActivarPorCodigoAsync(producto);
        }
    }
}
