//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pymex.MVC.AlmacenProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDataContract", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pymex.MVC.AlmacenProxy.ResponseWithDataDataContractOfAlmacenDCXmnxQzc5))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pymex.MVC.AlmacenProxy.ResponseWithDataDataContractOfArrayOfAlmacenDCXmnxQzc5))]
    public partial class ResponseDataContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsCorrectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsCorrecto {
            get {
                return this.EsCorrectoField;
            }
            set {
                if ((this.EsCorrectoField.Equals(value) != true)) {
                    this.EsCorrectoField = value;
                    this.RaisePropertyChanged("EsCorrecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithDataDataContractOfAlmacenDCXmnxQzc5", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ResponseWithDataDataContractOfAlmacenDCXmnxQzc5 : Pymex.MVC.AlmacenProxy.ResponseDataContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.AlmacenProxy.AlmacenDC DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pymex.MVC.AlmacenProxy.AlmacenDC Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithDataDataContractOfArrayOfAlmacenDCXmnxQzc5", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ResponseWithDataDataContractOfArrayOfAlmacenDCXmnxQzc5 : Pymex.MVC.AlmacenProxy.ResponseDataContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pymex.MVC.AlmacenProxy.AlmacenDC[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pymex.MVC.AlmacenProxy.AlmacenDC[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlmacenDC", Namespace="http://schemas.datacontract.org/2004/07/Pymex.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class AlmacenDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AforoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Aforo {
            get {
                return this.AforoField;
            }
            set {
                if ((this.AforoField.Equals(value) != true)) {
                    this.AforoField = value;
                    this.RaisePropertyChanged("Aforo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlmacenProxy.IAlmacenService")]
    public interface IAlmacenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_AlmacenDC/Listar", ReplyAction="http://tempuri.org/IGenericServiceOf_AlmacenDC/ListarResponse")]
        Pymex.MVC.AlmacenProxy.ResponseWithDataDataContractOfArrayOfAlmacenDCXmnxQzc5 Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_AlmacenDC/Listar", ReplyAction="http://tempuri.org/IGenericServiceOf_AlmacenDC/ListarResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.AlmacenProxy.ResponseWithDataDataContractOfArrayOfAlmacenDCXmnxQzc5> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_AlmacenDC/ObtenerPorId", ReplyAction="http://tempuri.org/IGenericServiceOf_AlmacenDC/ObtenerPorIdResponse")]
        Pymex.MVC.AlmacenProxy.ResponseWithDataDataContractOfAlmacenDCXmnxQzc5 ObtenerPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_AlmacenDC/ObtenerPorId", ReplyAction="http://tempuri.org/IGenericServiceOf_AlmacenDC/ObtenerPorIdResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.AlmacenProxy.ResponseWithDataDataContractOfAlmacenDCXmnxQzc5> ObtenerPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_AlmacenDC/Crear", ReplyAction="http://tempuri.org/IGenericServiceOf_AlmacenDC/CrearResponse")]
        Pymex.MVC.AlmacenProxy.ResponseDataContract Crear(Pymex.MVC.AlmacenProxy.AlmacenDC dataContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_AlmacenDC/Crear", ReplyAction="http://tempuri.org/IGenericServiceOf_AlmacenDC/CrearResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.AlmacenProxy.ResponseDataContract> CrearAsync(Pymex.MVC.AlmacenProxy.AlmacenDC dataContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_AlmacenDC/Actualizar", ReplyAction="http://tempuri.org/IGenericServiceOf_AlmacenDC/ActualizarResponse")]
        Pymex.MVC.AlmacenProxy.ResponseDataContract Actualizar(Pymex.MVC.AlmacenProxy.AlmacenDC dataContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_AlmacenDC/Actualizar", ReplyAction="http://tempuri.org/IGenericServiceOf_AlmacenDC/ActualizarResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.AlmacenProxy.ResponseDataContract> ActualizarAsync(Pymex.MVC.AlmacenProxy.AlmacenDC dataContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteOperationOf_AlmacenDC/Eliminar", ReplyAction="http://tempuri.org/IDeleteOperationOf_AlmacenDC/EliminarResponse")]
        Pymex.MVC.AlmacenProxy.ResponseDataContract Eliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteOperationOf_AlmacenDC/Eliminar", ReplyAction="http://tempuri.org/IDeleteOperationOf_AlmacenDC/EliminarResponse")]
        System.Threading.Tasks.Task<Pymex.MVC.AlmacenProxy.ResponseDataContract> EliminarAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlmacenServiceChannel : Pymex.MVC.AlmacenProxy.IAlmacenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlmacenServiceClient : System.ServiceModel.ClientBase<Pymex.MVC.AlmacenProxy.IAlmacenService>, Pymex.MVC.AlmacenProxy.IAlmacenService {
        
        public AlmacenServiceClient() {
        }
        
        public AlmacenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlmacenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pymex.MVC.AlmacenProxy.ResponseWithDataDataContractOfArrayOfAlmacenDCXmnxQzc5 Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.AlmacenProxy.ResponseWithDataDataContractOfArrayOfAlmacenDCXmnxQzc5> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public Pymex.MVC.AlmacenProxy.ResponseWithDataDataContractOfAlmacenDCXmnxQzc5 ObtenerPorId(int id) {
            return base.Channel.ObtenerPorId(id);
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.AlmacenProxy.ResponseWithDataDataContractOfAlmacenDCXmnxQzc5> ObtenerPorIdAsync(int id) {
            return base.Channel.ObtenerPorIdAsync(id);
        }
        
        public Pymex.MVC.AlmacenProxy.ResponseDataContract Crear(Pymex.MVC.AlmacenProxy.AlmacenDC dataContract) {
            return base.Channel.Crear(dataContract);
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.AlmacenProxy.ResponseDataContract> CrearAsync(Pymex.MVC.AlmacenProxy.AlmacenDC dataContract) {
            return base.Channel.CrearAsync(dataContract);
        }
        
        public Pymex.MVC.AlmacenProxy.ResponseDataContract Actualizar(Pymex.MVC.AlmacenProxy.AlmacenDC dataContract) {
            return base.Channel.Actualizar(dataContract);
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.AlmacenProxy.ResponseDataContract> ActualizarAsync(Pymex.MVC.AlmacenProxy.AlmacenDC dataContract) {
            return base.Channel.ActualizarAsync(dataContract);
        }
        
        public Pymex.MVC.AlmacenProxy.ResponseDataContract Eliminar(int id) {
            return base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task<Pymex.MVC.AlmacenProxy.ResponseDataContract> EliminarAsync(int id) {
            return base.Channel.EliminarAsync(id);
        }
    }
}
